### ISSUE TITLE
Difficulty generating static HTML from ecore model

### ISSUE THREAD

**Issue by vasib** [Nasdanika/vinci#1]
I was trying to generate a static HTML site from an ecore model but I face an issue.
From what I gather the ecore model must first be converted to a Vinci action model, and from that the HTML site can be generated.

I used `nsd.exe` from [Nasdanika Tool Suite](https://nasdanika.org/builds/master/index.html) on my ecore model (with nsURI=http://www.test.com) like so:
```
nsd.exe vinci generate documentation ecore -o ecore-doc http://www.test.com
```
But I get this error:
```
java.lang.IllegalArgumentException: Gen model not found for NS URI http://www.test.com
```

I don't understand why, or what kind of genmodel is needed, but I generated a normal genmodel and I still get the same error.
I also tried putting the ecore model in the same folder as `nsd.exe` and running from that folder with the same result.

**Comment by pvlasov** [comment]
Hi Bogdan,

Thank you for your interest in Vinci! The error is caused by the fact that nsd.exe eclipse installation has no awareness of your model - you need to install your model plug-in into your installation of Nasdanika Tool Suite. For this you'd need to create a feature, ... - it is a bit involved process.

Because of this and also because Vinci is not actively developed anymore I suggest that you use https://docs.nasdanika.org/html/ecore/index.html, the easiest way is to clone and adjust https://github.com/Nasdanika/ecoredoc-test. Shall you face issues - let me know and I'll create a simple demo of ecore doc which generates documentation from a single model.

I'm going to archive this repository, so please create further issues in ecoredoc-test or html repositories.
